# Site settings
title: Emily Friis
description: A portfolio for Emily Friis
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Emily Friis
user_description: Passionate student studying towards a diploma in web development at NMIT.
user_title: Software Developer
email: emilyfriis4@gmail.com
twitter_username: lorem_ipsum
github_username:  emfriis
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
